all:
  children:
    linux:
      hosts:
        linuxhost1:
          ansible_host: 34.230.132.92
        linuxhost2:
          ansible_host: 3.92.61.42
    windows:
      hosts:
        winhost1:
          ansible_host: 52.201.35.75
        winhost2:
          ansible_host: 23.22.78.38
